### ISSUE TITLE
Database getting to large

### ISSUE THREAD

**Issue by lloydbates** [Sonaza/TokenPrice#2]
![grafik](https://user-images.githubusercontent.com/4516420/99681810-def86a00-2a7e-11eb-856f-c32e1687cf0d.png)
![grafik](https://user-images.githubusercontent.com/4516420/99681889-f20b3a00-2a7e-11eb-8091-53ce0c00c0dd.png)

I'm using your DataBroker Plugin for quite some time now, and the database is getting rather large.  
For know I opted to just reset the database, _loosing_ historical data, but there shouldn't be a need for having this large amount of data.

Could you implement some kind of log cleaning, keeping only the last X days worth of data?

**Comment by Sonaza** [comment]
Should remove all entries older than 72 hours now upon addon start (on login/ui reloads).
